export const themes = {
  sakura: {
    primary: '#D32F2F',
    onPrimary: '#FFFFFF',
    primaryContainer: '#FFCDD2',
    onPrimaryContainer: '#B71C1C',
    background: '#FFF8F9',
    surface: '#FFFFFF',
    surfaceVariant: '#FCE4EC',
    onSurface: '#1F1A1C',
    onSurfaceVariant: '#49454F',
    outline: '#E0E0E0',
    outlineVariant: '#CAC4D0',
  },
  mint: {
    primary: '#00695C',
    onPrimary: '#FFFFFF',
    primaryContainer: '#B2DFDB',
    onPrimaryContainer: '#004D40',
    background: '#F2FBF9',
    surface: '#FFFFFF',
    surfaceVariant: '#E0F2F1',
    onSurface: '#00201A',
    onSurfaceVariant: '#404943',
    outline: '#CCEBE8',
    outlineVariant: '#BDBDBD',
  },
  ocean: {
    primary: '#1565C0',
    onPrimary: '#FFFFFF',
    primaryContainer: '#BBDEFB',
    onPrimaryContainer: '#0D47A1',
    background: '#F4F8FC',
    surface: '#FFFFFF',
    surfaceVariant: '#E3F2FD',
    onSurface: '#0D1B2A',
    onSurfaceVariant: '#41484D',
    outline: '#D1E4F6',
    outlineVariant: '#C2C7CF',
  }
};
